# Generated by Django 2.2.10 on 2020-03-25 14:21

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='问题内容'),
        ),
    ]
