# Generated by Django 2.2.10 on 2020-03-26 12:01

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0002_auto_20200325_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='答案内容'),
        ),
    ]
