# Generated by Django 2.2.10 on 2020-03-28 15:58

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0004_auto_20200328_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='问题内容'),
        ),
    ]
