# Generated by Django 2.2.10 on 2020-03-22 04:35

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='多个标签使用英文逗号(,)隔开', through='blogs.UUIDTaggedItem', to='taggit.Tag', verbose_name='文章标签'),
        ),
    ]
