# Generated by Django 2.2.10 on 2020-03-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200322_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1, verbose_name='文章状态'),
        ),
    ]
